language: php

php:
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

script:
  - composer check
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/php-coveralls
