language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text
  - composer check