language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --coverage-clover build/logs/clover.xml

script:
  - composer check
  - ./vendor/bin/phpunit --coverage-text

after_success:
  - travis_retry vendor/bin/php-coveralls
